### ISSUE TITLE
Auth story?

### ISSUE THREAD

**Issue by apendleton** [mapbox/Hecate#13]
It looks like Hecate preserves the OSM distinction between publicly accessible read-only content and auth-required read-write access. I wonder if this makes sense going forward. If a usecase for this service is potentially store internal-use/private data, reads would also need to be protected. It seems like, freed from the constraints of OSM's code, you'd either want to secure everything at the network level, or everything with username/password, but I'm not sure why you'd additional levels of auth/protection for some parts of the service than for others. Maybe it's just a constraint imposed by a desire to still interoperate with JOSM?

**Comment by ingalls** [comment]
@apendleton yup, as you mention above - the auth story has to duplicate that of OSM to enjoy the benefits of using JOSM/iD.

Current approach is to secure at the network level via VPC/ssh policy.

**Comment by ingalls** [comment]
Hecate auth is now fully customizable per the `Custom Authentication` section of the readme
