### ISSUE TITLE
Should the API be verisoned?

### ISSUE THREAD

**Issue by apendleton** [mapbox/Hecate#14]
While recognizing that there's some contention in how best to represent versioning of APIs over time, it still seems like common practice to put version numbers in URLs. The OSM part of the API is versioned to match the current OSM version but other parts of the API are not. Were we to write scripts that interacted with the API, it might be nice to be able to easily enforce their compatibility as the underlying API might change out from under them, and a version number seems like a good way to do that. (Also, it might be nice to more clearly separate the URL namespaces of the OSM compat part of the API from the "native" part?)

**Comment by ingalls** [comment]
Going to close for now and follow the approach that MapServer has taken where servers report their version and clients are expected to check compatibility.

Should the need arise to have multiple supported versions of the API we will start Versioning with `v2` of the api, prefixing all of the current API endpoints with `v2/`
