### ISSUE TITLE
Unable to retrieve metadata for certain point features

### ISSUE THREAD

**Issue by lizziegooding** [mapbox/Hecate#158]
### Context

While exploring some of the addresses we have loaded into Hecate, I noticed that I was unable to retrieve metadata information for some point features. I'm not seeing any errors in the console and there doesn't appear to be any pattern to the point features that do/do not return.

![Apr-02-2019 15-26-28](https://user-images.githubusercontent.com/18095166/55430317-cb238b80-555b-11e9-8904-31ac9d967450.gif)

cc/ @ingalls

**Comment by ingalls** [comment]
This should now be resolved with our improved VT Generation
