### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by chazanov** [mapbox/Hecate#163]
Since there was no INSTALL file I've just run `cargo build --release`

This fails due to unsupported `proc_macro`. My rust is 1.33, so this shouldn't be too old??

How may I correctly compile _hecate_?

cc/ @ingalls

**Comment by ingalls** [comment]
Please take a look at the [Build Environment](https://github.com/mapbox/Hecate#build-environment) section of the README. Compiling hecate will require nightly at this time.
