### ISSUE TITLE
Features failing to render in Hecate UI

### ISSUE THREAD

**Issue by lizziegooding** [mapbox/Hecate#167]
### Context

@samely and I noticed that certain features weren't being rendered in the Hecate UI, though they were queryable. See the following errors in the console:
<img width="1440" alt="Screen Shot 2019-05-24 at 12 21 32 PM" src="https://user-images.githubusercontent.com/18095166/58342487-7cd58f00-7e1e-11e9-8e9f-7ae7594faeb6.png">

The address we were looking for is `900 Windemere Cir, Longview, Texas 75601, United States`, z/x/y `19.39/32.5103247/-94.6816671`

cc/ @ingalls

**Comment by ingalls** [comment]
This should be fixed in Hecate@0.70.x which updates the required postgis version and switches to use `ST_AsMVT` instead of the rust based VT generation
