### ISSUE TITLE
OSM (PBF) file export

### ISSUE THREAD

**Issue by chazanov** [mapbox/Hecate#173]
### Context
Does hecate support the export of _osm.pbf_ files? This is what the official server does; I would like to have this to create Mapnik tiles from data inside a hecate instance.

cc/ @ingalls

**Comment by ingalls** [comment]
@chazanov - No Hecate is designed to support streaming GeoJSON. It currently does not support the export of OSM Binary formats. 

We typically stream the GeoJSON directly to [tippecanoe](https://github.com/mapbox/tippecanoe) which is more flexible for creating Mapbox Vector Tiles.

**Comment by ingalls** [comment]
Closing for now, feel free to open another ticket if you have any questions.

Note that hecate also has built in Mapbox Vector Tile Creation
