### ISSUE TITLE
Rewrite Delta History API Documentation

### ISSUE THREAD

**Issue by ingalls** [mapbox/Hecate#208]
### Context

There are a couple of bugs in the documentation for the delta history api

For example
```
offset=delta id
```

Ref: https://github.com/mapbox/hecate#get-apideltas

### Next Actions

Rewrite this chunk of documentation to be clearer and also review the format for representing API parameters for consistency with newer sections of the documentation

cc/ @ingalls

**Comment by miccolis** [comment]
Addressed w/ https://github.com/mapbox/Hecate/pull/211
