### ISSUE TITLE
State of this Project?

### ISSUE THREAD

**Issue by anlumo** [mapbox/Hecate#223]
Hello,

What is the state of this project? I can see that the last commit was 8 months ago, but there's no note of abandonment. Is this still being developed?

cc/ @ingalls

**Comment by ingalls** [comment]
Hey @anlumo, I'm the chief dev of the project, the project is very much alive and under active community development here: https://github.com/hecate/hecate 

I've been very busy the last couple months release V4 of the [OpenAddresses Platform](https://batch.openaddresses.io/data) but should be circling back to focus my time on Hecate within the next month or two.

**Comment by anlumo** [comment]
Great, thank you!
