### ISSUE TITLE
Add GeoJSON validator

### ISSUE THREAD

**Issue by samely** [mapbox/Hecate#35]
Per convo with @ingalls :computer:  

:hole: There is no way to identify where/why a corrupted `.geojson` file fails while importing whit the current message we get. 

<details>
<Summary>Case</Summary>

```
ok - beginning upload of 1595 features
ok - upload complete
ok - beginning upload of 1593 features

Upload Error: Uploaded to Line 1595
Body must be valid GeoJSON Feature
```
</details>

###

### Suggested resource
:point_right: [geojsonhint](https://github.com/mapbox/geojsonhint)

### Next steps
- [ ] Add geoJSON validator

**Comment by ingalls** [comment]
Hecate already validates GeoJSON via rust-geojson. It is up to the importing library to validate before they send to the server to avoid an error.
